### ISSUE TITLE
Missing bins should not be fatal

### ISSUE THREAD

**Issue by dan-wittenberg** [puppetlabs/pdk#253]
pdk (FATAL): Failed to generate binstubs for 'rubocop':
Could not find gem 'rubocop'.

If you don't want to use or can't install a requisite, it should be a warning and not fatally stop the checks

**Comment by DavidS** [comment]
When the developer requests a specific check (even if just through defaulting to "all"), the absence of the tool is a fatal error, as the correctness of the target cannot be ascertained without it.

A possibility is still running all the other checks, and still returning a non-zero exit code, or providing configuration to disable certain checks at the PDK level. In any case it would not be a recommended workflow.

**Comment by dan-wittenberg** [comment]
At the least disable certain checks, I was running the default validate to get that error, so I didn't specifically call that test.

**Comment by DavidS** [comment]
The recommended default case is to run `pdk validate` on the command line, and in CI, and the tool is expected to run all checks in this case. Especially in CI, if the environment is not set up correctly, the pdk **has** to fail with an error.

Since you can use `pdk validate metadata,puppet` to not run rubocop, if you really have to skip it, I'll close this ticket.
