### ISSUE TITLE
add in readline support to ruby

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/pdk#305]
The ruby bundled with pdk seems to not have readline support compiled in.

**Comment by DavidS** [comment]
1. the bundled ruby is the AIO puppet agent ruby, I would not be surprised if that doesn't have readline
2. what's your usecase?

**Comment by logicminds** [comment]
It doesn't appear to have readline support compiled in.

`/opt/puppetlabs/pdk/private/ruby/2.1.9/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- readline (LoadError)`

I am trying to install the puppet debugger gem which requires readline support.  The puppet-agent ruby has readline built in and works just fine.  So the pdk ruby is different.

**Comment by DavidS** [comment]
You are totally right. Investigating this uncovered a few more components that are missing from the pdk packaging. We'll aim to include that in our next release after puppetconf.

I've created https://tickets.puppetlabs.com/browse/PDK-576 to track that.

Meanwhile you could use the pdk gem (instead of the native packaging) and use your system ruby to host it. I haven't had issues with Debian's 2.3 ruby from testing on my workstation for example.

**Comment by logicminds** [comment]
I can't add puppet-debugger in the Gemfile until this is fixed.  Responding to earlier private tweet

**Comment by DavidS** [comment]
Another related problem I've stumbled over while playing around with this, is the fact that the vendored rgen in the vendored puppet in puppet-retrospec causes paths with more than 256 characters, which breaks the package build.

**Comment by DavidS** [comment]
This has been fixed in 1.2.1 via https://github.com/puppetlabs/pdk-vanagon/commit/e800c341d2e30c80795c9b2d0425667829dcc04a
