### ISSUE TITLE
Missing Task Metadata validation in CI test.

### ISSUE THREAD

**Issue by ragnarkon** [puppetlabs/pdk#372]
It appears as though that the Travis CI file on generated modules doesn't include a step to validate the JSON metadata for Puppet Tasks.  There is no rake task available for Puppet Task validation, and utilizing `bundle exec metadata-json-lint tasks/*.json` isn't a valid alternative other than as a much-less-than-perfect check to ensure the JSON syntax itself is correct.

It would be beneficial to add a rake task that allows for validation of Puppet Tasks.

(Perhaps it is appropriate for this issue to be filed under the puppetlabs_spec_helper project instead?)

**Comment by scotje** [comment]
We are currently working on updating the generated Travis and Appveyor configs to use PDK to test the module instead of the rake tasks, at which point the task metadata will be checked by `pdk validate`.

This work is tracked in JIRA at https://tickets.puppetlabs.com/browse/PDK-709

**Comment by sanfrancrisko** [comment]
I feel [PDK-709](https://tickets.puppetlabs.com/browse/PDK-709) is discussing the implementation of `pdk validate` in to CI configs, but this issue is a request to add support for validating tasks. I've raised #1064 to capture that particular request and I will be trying to determine the best way forward for [PDK-709](https://tickets.puppetlabs.com/browse/PDK-709) too. However, for the meantime, I think it's good to have these tracked as separate discussions.
