### ISSUE TITLE
PDK 1.5.0 consufing error when cert invalid

### ISSUE THREAD

**Issue by TheMeier** [puppetlabs/pdk#510]
When you use a custom CA and install pdk from a package you have to manually add your custom root ca to cert.pem
When you upgrade the package you have to repeat that step.
When you run `pdk update` without  the right certificate you might get this error:

```
pdk (WARN): Unable to access the previously used template 'https://git.server/repo.git', using the default template instead.
/opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/module/templatedir.rb:189:in `validate_module_template!': The specified template 'https://git.server/repo.git' is not a directory. (ArgumentError)
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/module/templatedir.rb:59:in `initialize'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/module/convert.rb:71:in `new'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/module/convert.rb:71:in `stage_changes!'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/module/update.rb:9:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/cli/update.rb:29:in `block (2 levels) in <module:CLI>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:329:in `run_this'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:269:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/cri-2.10.1/lib/cri/command.rb:287:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/lib/pdk/cli.rb:18:in `run'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/lib/ruby/gems/2.4.0/gems/pdk-1.5.0/exe/pdk:6:in `<top (required)>'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/bin/pdk:23:in `load'
	from /opt/puppetlabs/pdk/private/ruby/2.4.4/bin/pdk:23:in `<main>'

```

This is very confusing, instead pdk should report there is an TLS issue here. Another point here is why not use the system ca-cert-bundle in the first place.

**Comment by msurato** [comment]
Our team is also experiencing this issue. During our testing we install modules from an internal repository. The workaround of adding our internal CA to the cert.pem file does resolve this issue, but using the system CA store would be preferred.

**Comment by scotje** [comment]
If folks are still experiencing this issue, can you try setting `http.sslCAInfo` and/or `http.sslCAPath` in your global `.gitconfig`? PDK's internal git client should respect those settings, please let us know if not.

**Comment by reusch** [comment]
Problem still exists in version 1.10.0:

$ git config --system --list
http.sslcainfo=/etc/ssl/ca-bundle.pem
$ /opt/puppetlabs/pdk/private/git/bin/git config --system --list
fatal: unable to read config file '/opt/puppetlabs/pdk/private/git/etc/gitconfig': No such file or directory
$ strings /opt/puppetlabs/pdk/private/git/bin/git | grep gitconfig
~/.gitconfig
~/.gitconfig
etc/gitconfig         <-- without leading / !
~/.gitconfig

Maybe you could reopen this issue since the problem still exists?
Or: is there a way to configure pdk to use system git?

**Comment by scotje** [comment]
Ah, yes it looks like PDK's git is configured to look for system level config at `/opt/puppetlabs/pdk/private/git/etc/gitconfig`.

To me it seems like PDK should just use your system `/etc/gitconfig` if you have one, so we can modify the way we compile `git` to look there instead. @rodjek @glennsarti any reason why we shouldn't just use `/etc/gitconfig` instead of `/opt/puppetlabs/pdk/private/git/etc/gitconfig`?

@reusch in the meantime, it looks like PDK's git will look at `~/.gitconfig`, can you try setting the `http.sslCAInfo` and/or `http.sslCAPath` settings at the user level and see if that helps?

**Comment by scotje** [comment]
Created https://tickets.puppetlabs.com/browse/PDK-1378 to track this in JIRA.

**Comment by reusch** [comment]
@scotje: yes, at the moment I (we) use the user gitconfigs.

**Comment by scotje** [comment]
OK, I think we will have a fix in the next release that will make it look at `/etc/gitconfig`.

**Comment by msurato** [comment]
@scotje will the proposed fix also work for PDK on Windows?

**Comment by scotje** [comment]
@msurato To clarify, the fix here is that PDK's vendored `git` binary will now read from an existing system-level `gitconfig` file. But you still need to add the `http.sslCAInfo` and/or `http.sslCAPath` settings to your `gitconfig` in order to have `git` use your preferred CA certs.

On Windows the system `gitconfig` path for the vendored PDK Git is `%ProgramFiles\Puppet Labs\DevelopmentKit\private\git\mingw64\etc\gitconfig` if you don't have a standalone "Git for Windows" installation and `%ProgramFiles%\Git\mingw64\etc\gitconfig` if you do have a standalone "Git for Windows" installation.

To change either of those you will need Administrator privileges, but an easier option might to to change the setting at the user level:

```
%ProgramFiles\Puppet Labs\DevelopmentKit\private\git\cmd\git.exe config --global http.sslCAInfo <path to your custom CA cert bundle>
```

**Comment by scotje** [comment]
This article has some more info about using custom CA certs with Git for Windows: https://blogs.msdn.microsoft.com/phkelley/2014/01/20/adding-a-corporate-or-self-signed-certificate-authority-to-git-exes-store/

**Comment by jfridgen** [comment]
@scotje We have "Git for Windows" installed with the following relevant settings in the `gitconfig` stored at `%ProgramFiles%\Git\mingw64\etc\gitconfig`.
```
[http]
  sslBackend = schannel
[credential]
  helper = manager
```
It appears that PDK defaults to the private `gitconfig` at `%ProgramFiles\Puppet Labs\DevelopmentKit\private\git\mingw64\etc\gitconfig` and does not use the `gitconfig` at `%ProgramFiles%\Git\mingw64\etc\gitconfig`.

I tested this by confirming I do not receive the SSL cert error if I add the above settings to `%ProgramFiles\Puppet Labs\DevelopmentKit\private\git\mingw64\etc\gitconfig`, or if I remove the private Git install altogether, but do receive the error otherwise.

Looks like it may relate to the line [here](https://github.com/puppetlabs/pdk/blob/18721c41d435e06482281f2dc1608d590ef23a30/lib/pdk/util/git.rb#L42) where it seems to default to the private Git install and only falls back to the "Git for Windows" install if it can't find the private Git.

Any chance the behavior could be updated so it uses the system `gitconfig` from "Git for Windows" as the default if it exists?

**Comment by scotje** [comment]
Interesting. Does `%ProgramFiles\Puppet Labs\DevelopmentKit\private\git\mingw64\etc\gitconfig` exist on your system and if so what is in it? The behavior I saw on my testing VM was the PDK-vendored GfW would use that file if it was there but fall back to looking at `%ProgramFiles%\Git\mingw64\etc\gitconfig` if not. 

If that's the case we may just need to make sure our packaging doesn't place the `%ProgramFiles\Puppet Labs\DevelopmentKit\private\git\mingw64\etc\gitconfig` file assuming there are no meaningful settings it it by default.

**Comment by scotje** [comment]
Ooo, maybe we can set up the vendored `gitconfig` to include the default GfW path: https://git-scm.com/docs/git-config#_includes

**Comment by scotje** [comment]
Something like:

```
[include]
	path = "C:\\Program Files\\Git\\mingw64\\etc\\gitconfig"
```

at the bottom of the vendored `gitconfig` seems to work. Only downside is that we have to hard-code the `C:\Program Files` bit since `git-config` doesn't expand variables...

**Comment by scotje** [comment]
To add more complexity to the situation, there are potentially three different `--system` paths on Windows:

```
For msysGit: %ProgramFiles(x86)%\Git\etc\gitconfig
For Git for Windows (64 bit): %ProgramFiles%\Git\mingw64\etc\gitconfig
For MSYS2-native git: [MSYS2-install-path]\etc\gitconfig
```

Plus! There is also `%PROGRAMDATA%\Git\config` which was decided back in 2015 would be the shared config location between Git for Windows and libgit2. (https://github.com/git-for-windows/git/commit/153328ba92ca6cf921d2272fa7e355603cbf71b7)

Maybe we should just `include` that shared location and document that people should use that? Unfortunately it also has the lowest precedence of any of them...

**Comment by scotje** [comment]
@glennsarti @jpogran Thoughts on what we should do here on Windows?

**Comment by scotje** [comment]
I'm kind of leaning towards just documenting that users should customize their `gitconfig` at the user-level and PDK will respect that, and that they can add an `[include]` to their user-level config that points to an existing `gitconfig` from another installation if they want.

**Comment by jfridgen** [comment]
Thanks for the quick responses.  Is there a reason the PDK-vendored Git needs to be used at all if the user already has Git for Windows installed (i.e. is it just provided for convenience if the user doesn't already have Git installed, or is it customizing Git in a way necessary for PDK to work correctly)?

If the former, can PDK default to the Git for Windows EXE if it's installed and fallback to the PDK-vendored Git EXE if not (instead of the opposite which it seems to do today)?  Then it would use the Git for Windows system gitconfig if the users already had Git for Windows installed, which they've likely already setup correctly for SSL.  Users without Git for Windows could still be instructed to update their user-level gitconfig if needed.

**Comment by scotje** [comment]
Yeah, the reason we prefer the vendored Git is that we can have confidence about the version and features it supports as well as be reasonably sure that it's configured in a sane way.

I think maybe the thing to do is let users decide which Git installation to prefer, add a configuration option like `useSystemGit=true`

We recently added some user config backend stuff so we should be able to add something like this relatively quickly. I'm going to create a followup ticket in JIRA to implement this, unless someone thinks it's a terrible idea. :)

**Comment by scotje** [comment]
I created https://tickets.puppetlabs.com/browse/PDK-1388 to track making the use of system-installed Git a configuration option.
