### ISSUE TITLE
'install --without group' not working

### ISSUE THREAD

**Issue by danielserrao** [puppetlabs/pdk#533]
Hi,

In my Gemfile I have something like;

```
...
group :check do
  gem 'rake', '12.3.0'
end
...
```

But when I use the command ``/usr/local/bin/pdk bundle -- install --without check``, the bundler installs everything including the gem rake which is only defined inside the group 'check'.

I was expecting to install everything but the gem rake. Am I doing something wrong?

Versions:
OS: RedHat 6
PDK: 1.5.0

Thanks for any help.

**Comment by bmjen** [comment]
Hi @danielserrao , since #466 was merged, you don't need to use the `--` anymore. 

`pdk bundle install --without check` should work. You may get a Gemfiile.lock error, but you can remove that and try again. If it completes, you should have a `.bundle/config` in your module directory that includes a variable of `BUNDLE_WITHOUT`.

**Comment by danielserrao** [comment]
Hi bmjen, thanks for your response, but when I don't use the ``--`` I get ``bundle: illegal option -- without`` which is strange since I'm using a PDK version that should have this resolved.

**Comment by bmjen** [comment]
@danielserrao can you try it with 1.6.0?

**Comment by bmjen** [comment]
@danielserrao Have you gotten any resolution to this? `rake` is a core dependency for PDK, so it will be installed regardless of where else you have it.

**Comment by rodjek** [comment]
I'm going to close this out due to a lack of activity. Please feel free to reopen this issue if you're still experiencing this problem with the latest version of PDK.
