### ISSUE TITLE
default_facts.yml does not override values from facterdb

### ISSUE THREAD

**Issue by mmerfort** [puppetlabs/pdk#628]
**Describe the bug**
The values in the file `spec/default_facts.yml` do not override the default values provided by the facterdb gem.

**To Reproduce**
1. Create a new project with pdk
2. Create a resource using a fact value, which is set in `default_facts.yml`.
3. Write a test where you test for that value.

Code: https://gist.github.com/mmerfort/c0a3bb1e9ad7afe7601e9dc5acc4aef9

**Expected behavior**
I would expect the tests to run through but instead they fail because the fact value isn't set correctly.

**Additional context**
- PDK was installed from https://aur.archlinux.org/packages/pdk/
- PDK version 1.9.0
- Arch Linux x86_64

**Comment by scotje** [comment]
@mmerfort As far as I can tell this is expected behavior, in that facts set in the `let(:facts)` block inside of an example will override any values found in the `default_facts` file.

You can drop the `ipaddress` fact from the applied `os_facts` hash by modifying the `let(:facts)` block as shown below:

```ruby
let(:facts) do
  os_facts.reject { |fact, _| fact == :ipaddress }
end
```

**Comment by scotje** [comment]
Closing this issue as this appears to currently be the expected behavior. This is definitely an area where we would like to improve the documentation and clarity of how tests are expected to be written.
