### ISSUE TITLE
pdk 1.9.1.0 on windows does not set path env variable

### ISSUE THREAD

**Issue by c33s** [puppetlabs/pdk#641]
after installing pdk and running pdk i get a `'pdk' is not recognized as an internal or external command, operable program or batch file.` because none of the needed paths where added to the `PATH` env variable.
also tried to repair my installation. same result. no path env set.

**Additional context**
- pdk 1.9.1.0 (from `C:\Program Files\Puppet Labs\DevelopmentKit\PDK_VERSION`)
- win7x64

side question: what are the exact paths which should be added during the installation (so i can simply add them by myself)?

**Comment by c33s** [comment]
also tested on win10, after installation the path variable for system and the user is the same as before.

**Comment by scotje** [comment]
@c33s did you launch a new PowerShell session after installation? The PDK interface on Windows is implemented by a PowerShell module which should be auto-loaded in new PowerShell sessions after install (starting with PowerShell 4). 

On PowerShell 2 or 3 you will have to manually load the module, which is documented here: https://puppet.com/docs/pdk/1.x/pdk_install.html#task-3944

**Comment by c33s** [comment]
does this mean it won't work without powershell? -.-
i am using `cmd.exe` (with https://cmder.net/) and mainly `bash.exe`

is there some way around this issue or is the whole windows part powershell script? 

but even my tries with powershell fail:
```
PS C:\Program Files\Cmder> Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser
PS C:\Program Files\Cmder> Import-Module -Name "$($env:ProgramFiles)\WindowsPowerShell\Modules\PuppetDevelopmentKit"
PS C:\Program Files\Cmder> pdk
C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.5/lib/ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem pdk (>= 0.a) (Gem::GemNotFoundException)
        from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.5/lib/ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
        from C:/PROGRA~1/PUPPET~1/DEVELO~1/private/ruby/2.4.5/bin/pdk:23:in `<main>'
```

**Comment by scotje** [comment]
@glennsarti do you have any ideas about why the PowerShell invocation of PDK above isn't working?

**Comment by jpogran** [comment]
cmder is a superset of conemu, and purposely does things in it's own opinionated way, which may not work with other tools. it has own powershell profile it loads instead of the user profile, and it changes environment variables and PATH. It's likely interfering with the env variables our module relies on.

That being said, latest cmder, powershell 5.1 and pdk 1.9.0 works for me:

![image](https://user-images.githubusercontent.com/272569/55496607-81937900-560d-11e9-8c8e-d17351053d10.png)

**Comment by c33s** [comment]
first of all, thank you all for your comments. it is really awesome that you have taken you time.

just for information, for the tests i started powershell via the start menu (windows native without cmder)

where would be the best place to open a ticket for "native exe support"? being locked into powershell is really uncool (really want to use bash). why not normally installing exe files which are placed in directories which is added to the path variable?
a powershell dependency is quite restrictive. also because i prefer to disable powershell scripting. https://www.heise.de/security/meldung/Studie-Angreifer-lieben-Powershell-4357396.html (german) https://resources.redcanary.com/hubfs/ThreatDetectionReport-2019.pdf

do you know if it is possible to run pdk directly without powershell? as there is a `pdk.bat` shouldn't that work? if i look into `pdk` i see it is just ruby. any tips how the things are glued together and how to get to a working pdk without powershell?

**Comment by scotje** [comment]
@c33s it may be possible for you to come up with a way to invoke PDK without using the PowerShell wrapper. You can review the environment set up by the wrapper here: https://github.com/puppetlabs/pdk-vanagon/blob/master/resources/files/windows/PuppetDevelopmentKit/PuppetDevelopmentKit.psm1

We will of course consider your request for a non-PowerShell interface on Windows, however we can't make any specific promises for future support. Feel free to file an issue on the https://github.com/puppetlabs/pdk-planning repo to track that request.

This might also be a case where managing your own Ruby installation and using PDK as a Rubygem might be a better solution for you. That should work under WSL/bash and if you run into issues with that configuration we would likely consider those bugs and prioritize fixing them.

I'm going to close this issue because I don't think it represents a bug in the PDK itself. Thanks again for your constructive feedback!

**Comment by c33s** [comment]
@scotje but i have still the problem that pdk fails for me in native powershell

**Comment by scotje** [comment]
Is that still on Windows 7? What version of PowerShell?

**Comment by scotje** [comment]
I just performed a new PDK install on a fresh Windows 7 with PowerShell 2.0 and after running:

`Import-Module -Name "$($env:ProgramFiles)\WindowsPowerShell\Modules\PuppetDevelopmentKit"`

it invoked PDK successfully via the PowerShell console.
