### ISSUE TITLE
--verbose option broken for `pdk new defined_type`

### ISSUE THREAD

**Issue by gepandz** [puppetlabs/pdk#679]
**Describe the bug**
When running `pdk new defined_type -v <...>` or `pdk new --verbose defined_type <...>`, PDK returns `defined_type: unrecognized option -- v` or `... verbose`. It's a flag that appears in the `pdk help new` text.

**To Reproduce**
Run `pdk new defined_type -v mytype` in a PDK-configured system and module.

**Expected behavior**
Verbose output or normal output, ignoring an unused flag.

**Additional Context**
```
>  pdk --version
1.10.0
```

A bug is any difference from documented behavior. If there's a flag that's documented to work, and it doesn't, then it's probably best to either stub it out so it exits quietly or implement it, since it looks like this is an inherited flag that `pdk-new-defined_type` can't disable.

Needless to say, this is _not_ a high-priority bug... ;) Thanks!

**Comment by scotje** [comment]
Thanks for the report!

I agree that it's not clear that `--verbose` is an option only relevant to the `help` command and not to the command being described. Since that `help` content is being generated by the Cri library right now, we'll have to do a bit more work to resolve this.

I've created https://tickets.puppetlabs.com/browse/PDK-1396 to preliminarily track the work that would need to be done.

**Comment by scotje** [comment]
I also opened a related issue in the Cri project: https://github.com/ddfreyne/cri/issues/103

**Comment by scotje** [comment]
It appears that the `--verbose` option showing up was a Cri bug that has since been resolved. I have confirmed that the latest version of Cri no longer manifests this issue.
