### ISSUE TITLE
Yaml Syntax does not support ERB in YAML

### ISSUE THREAD

**Issue by salderma** [puppetlabs/pdk#683]
**Describe the bug**
Per https://github.com/puppetlabs/beaker/blob/139f10cd4c4992bd3f79e29e53ebae10733a2ef8/CHANGELOG.md#3350---2018-05-16, using Beaker Nodeset files that have ERB causes PDK yaml syntax failures.

**To Reproduce**
Add a yaml Beaker Nodeset file with ERB to the repo, run `pdk validate`...

Sample Beaker Nodeset File Snippet...
```
<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
<snip>
```
Execute PDK Validate (for yaml)...
```
$ pdk validate yaml
pdk (INFO): Using Ruby 2.5.3
pdk (INFO): Using Puppet 6.4.0
[✖] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"]).
error: yaml-syntax: spec/acceptance/nodesets/default.yml:8:6: mapping values are not allowed in this context 
```

**Expected behavior**
YAML check should pass or fail based on syntax, not presence of ERB.

**Comment by scotje** [comment]
I think what we will likely do is skip those files if they contain ERB because it will be very challenging to render them in the same way Beaker would and without doing that there will be no way to determine if the resulting YAML syntax is valid.

Created https://tickets.puppetlabs.com/browse/PDK-1395 to track this.

**Comment by cdenneen** [comment]
@scotje okay with skipping. 

Suggestion rather than skipping based on containing ERB would be more useful to have exclusion option for the yaml validation. So either some sort of `.yaml-validate.rc` or even better would be the option of a `.pdk-config.rc` where you could globally set include/excludes for multiple validators?

**Comment by sanfrancrisko** [comment]
There are a number of JIRA tickets and Github issues that are loosely around the theme of more customisation of the validators (specifically around the ability to define exclusions):

- [PDK-1132 ](https://tickets.puppetlabs.com/browse/PDK-1132)
- [PDK-663](https://tickets.puppetlabs.com/browse/PDK-663)
- #329 
- #341 

My thoughts are to start a discussion and define a piece of work that would satisfy as much (if not all) the requests in the various issues listed above.

**Comment by sanfrancrisko** [comment]
I've started a discussion here for any interested parties wanting to define how we go about implementing a global include/exclude list for all validators in the PDK: https://github.com/puppetlabs/pdk/discussions/1066
