### ISSUE TITLE
Problem between pdk and gitlab-ci

### ISSUE THREAD

**Issue by fduranti** [puppetlabs/pdk#702]
**Describe the bug**
gitlab-ci don't show only first 3 line of the output of pdk validate/unit testing.

**To Reproduce**
run pdk validate from gitlab ci
![image](https://user-images.githubusercontent.com/1173084/60766008-8ef44f80-a0a3-11e9-870e-22ff2130162f.png)

**Expected behavior**
The full  output should be shown.

**Additional context**
Your PDK installation method (native packages or via Rubygems)
- pdk-1.11.1.0-1.el7.x86_64
- gitlab-runner-12.0.1-1.x86_64
- gitlab-ee-12.0.3-ee.0.el7.x86_64

There's also a gitlab issue opened (not sure if the issue is from gitlab or pdk): https://gitlab.com/gitlab-org/gitlab-runner/issues/3570

**Comment by scotje** [comment]
Hi @fduranti, thanks for reporting this.

What is going on here is a bit of a mismatch between how things are being output. The first few lines you see when invoking the command (`pdk (INFO): ...`) are being written to the `STDERR` pipe since they are diagnostic output. Later on however, for not any good reason, the `info: task-name: ...` lines are being written to `STDOUT`, the reality is that those lines should probably also be being written to `STDERR`.

The net effect of changing those lines to output to `STDERR` as well would be that if the validation command did encounter any problems, the contents of `pdk_validate.txt` would be empty which may actually be the correct behavior. If you need a more complete (and machine readable) report of what was checked, that should exist in the `junit` XML-formatted report.

If you really want to capture the diagnostic output to a file, you can use output redirection to send `STDERR` to a file as well. (https://thoughtbot.com/blog/input-output-redirection-in-the-shell)

Please let us know if you have any further questions.

**Comment by fduranti** [comment]
@scotje the problem seems that the output in the gitlab runner is only those 4 lines (for this reason i do the cat reports/pdk_validate.txt (to see what is happening).
The normal output of the same command run interactively (not in gitlab ci) is this one:
`pdk (INFO): Running all available validators...                                                                                                                                                                                                                                           
pdk (INFO): Puppet Enterprise 2019.1 maps to Puppet 6.4.2.                                                                                                                                                                                                                                
pdk (INFO): Using Ruby 2.5.3                                                                                                                                                                                                                                                              
pdk (INFO): Using Puppet 6.4.2
[â] Checking metadata syntax (metadata.json tasks/*.json).
[â] Checking module metadata style (metadata.json).
[â] Checking YAML syntax (["**/*.yaml", "*.yaml", "**/*.yml", "*.yml"]).
[â] Checking Puppet manifest syntax (**/*.pp).
[-] Checking Puppet manifest style (**/*.pp).[
[

]
,
[

]
,
[

]
,
[

]
,
[

]
,
[

]
,
[

]
,
]
[â] Checking Puppet manifest style (**/*.pp).
[â] Checking Ruby code style (**/**.rb).
`

Not sure why there's all those [ ], but as you can see in the screenshot above  all the "checking" part is missing.

**Comment by fduranti** [comment]
@scotje There’s any other information you need to reproduce the issue?

**Comment by scotje** [comment]
@fduranti Are you saying that when there is a validation error there is no content in `reports/pdk_validate.txt` either? Are the failures reported in the JUnit XML report?

**Comment by fduranti** [comment]
@scotje seems I've found what my problem is.
I think I misread the help for "-f" option.
I was specifying a "-f junit:filename and -f text:filename" to report and save output artifact (and show them in gitlab merge request as junit output) but passing -f .... will remove stdout from the output and only show stderr (the stdout is managed and writtend to the files).
Passing another "-f text" will also show the correct stdout during the CI.

**Comment by scotje** [comment]
@fduranti glad you got it figured out! Let us know if there is anything we can update in the docs to make that behavior more clear.

**Comment by fduranti** [comment]
@scotje probably something that will state that it will overwrite the default standard output if defined and that a "-f text" will continue to output also to stdout.
