### ISSUE TITLE
'pdk test unit --verbose' does not change the rspec output format

### ISSUE THREAD

**Issue by natemccurdy** [puppetlabs/pdk#773]
**Describe the bug**
As per [the original feature request for making pdk test unit verbose by default](https://tickets.puppetlabs.com/browse/PDK-680?focusedCommentId=678885&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-678885), running `pdk test unit --verbose` should change rspec's output format from `progress` to `documentation`.

But in PDK 1.14.0, the `--verbose` flag doesn't do anything.

**To Reproduce**
1. Install PDK 1.14.0
1. Run `pdk test unit` and `pdk test unit --verbose`. Observe that the output doesn't change.

**Expected behavior**
1. `pdk test unit` uses rspec's `progress` format.
1. `pdk test unit --verbose` uses rspec's `documentation` format.

**Additional context**
- PDK 1.14.0 installed via puppet.com DMG

**Further Thoughts**

I'm realizing that this all will probably conflict with what's in the module's `./.rspec` file. The format can be defined there and I don't know if that should override or be overridden by the `pdk` command.

The standard PDK template lays down `--format documentation`:
https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.rspec.erb#L2

**Comment by scotje** [comment]
Good catch @natemccurdy, we are going to work to get the `--verbose` flag working in the next release!

> Further Thoughts
> 
> I'm realizing that this all will probably conflict with what's in the module's ./.rspec file. The format can be defined there and I don't know if that should override or be overridden by the pdk command.
> 
> The standard PDK template lays down --format documentation:
https://github.com/puppetlabs/pdk-templates/blob/master/moduleroot/.rspec.erb#L2

We were just discussing this and think the most reasonable long-term approach is:

- `pdk test unit`: respects whatever is set in your `.rspec` file (if present) otherwise defaults to `progress` format
- `pdk test unit --verbose`: overrides `.rspec` file and forces output to `documentation` format
- `pdk test unit --concise` (actual flag TBD): overrides `.rspec` file and forces output to `progress` format

And we would subsequently update `pdk-templates` to no longer specify a default output format in `.rspec`.

But these further changes will have to wait a bit until we can make some related updates so that we don't negatively affect people's CI output.
