### ISSUE TITLE
Support new bolt analytics path

### ISSUE THREAD

**Issue by adreyer** [puppetlabs/pdk#885]
Bolt has moved the default location of our analytics file as part of standardizing our config files.  
https://github.com/puppetlabs/bolt/issues/1843

For the time being will we support both the old and new locations though we may deprecate the old one in or before 3.0 depending on the timeline.

**Comment by DavidS** [comment]
- [ ] change https://github.com/puppetlabs/pdk/blob/d51ce5ebdf1a20b3751922ea5463e71c98613100/lib/pdk/config.rb#L187 to use the new path and fall back to the old path if there is no data at the new path.
- [ ] check the rest of the source to see if there is a different place where PDK is accessing the `analytics.yaml` file directly.

**Comment by scotje** [comment]
I think that should be the only place, basically we just look for a Bolt analytics config to copy the UUID if it exists, but if we can't find it we just generate our own.

**Comment by DavidS** [comment]
Looking at the change in https://github.com/puppetlabs/bolt/issues/1843 we would now have to replicate that behaviour and look in both locations as bolt doesn't migrate into the new path. Unless someone from the bolt team wants to step up and implement that, or fix bolt to migrate to a singular location, this won't get fixed in time for PDK2.0.
